"""add full schema

Revision ID: 6c8cf9afb42e
Revises: 0400302e4c5f
Create Date: 2026-08-26 12:41:41.708935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8cf9afb42e'
down_revision: Union[str, None] = '0400302e4c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('code3', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_name', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code3')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency', 'date', name='uq_rate_per_day')
    )
    op.create_index(op.f('ix_exchange_rates_base_currency'), 'exchange_rates', ['base_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_rates_target_currency'), 'exchange_rates', ['target_currency'], unique=False)
    op.create_table('hs_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('chapter', sa.String(length=2), nullable=False),
    sa.Column('heading', sa.String(length=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_codes_chapter'), 'hs_codes', ['chapter'], unique=False)
    op.create_index(op.f('ix_hs_codes_code'), 'hs_codes', ['code'], unique=True)
    op.create_index(op.f('ix_hs_codes_heading'), 'hs_codes', ['heading'], unique=False)
    op.create_index(op.f('ix_hs_codes_id'), 'hs_codes', ['id'], unique=False)
    op.create_table('duty_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hs_code_id', sa.Integer(), nullable=False),
    sa.Column('importing_country_id', sa.Integer(), nullable=False),
    sa.Column('exporting_country_id', sa.Integer(), nullable=True),
    sa.Column('basic_duty_rate', sa.Float(), nullable=True),
    sa.Column('additional_duty_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('cess_rate', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('WTO_MFN', 'FTA', 'MANUAL', 'INDIA_CUSTOMS', name='dutysource'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exporting_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.ForeignKeyConstraint(['importing_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_rates_hs_code_id'), 'duty_rates', ['hs_code_id'], unique=False)
    op.create_index(op.f('ix_duty_rates_id'), 'duty_rates', ['id'], unique=False)
    op.create_index(op.f('ix_duty_rates_importing_country_id'), 'duty_rates', ['importing_country_id'], unique=False)
    op.create_table('freight_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_country_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('SEA', 'AIR', name='freightmode'), nullable=False),
    sa.Column('container_type', sa.String(length=10), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_rates_destination_country_id'), 'freight_rates', ['destination_country_id'], unique=False)
    op.create_index(op.f('ix_freight_rates_effective_date'), 'freight_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_freight_rates_id'), 'freight_rates', ['id'], unique=False)
    op.create_index(op.f('ix_freight_rates_mode'), 'freight_rates', ['mode'], unique=False)
    op.create_index(op.f('ix_freight_rates_origin_country_id'), 'freight_rates', ['origin_country_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hs_code_confidence', sa.Float(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin_country_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_TRANSIT', 'CUSTOMS', 'DELIVERED', 'CANCELLED', name='shipmentstatus'), nullable=True),
    sa.Column('mode_of_transport', sa.Enum('SEA', 'AIR', 'ROAD', 'RAIL', name='transportmode'), nullable=True),
    sa.Column('incoterm', sa.Enum('EXW', 'FCA', 'FOB', 'CFR', 'CIF', 'DAP', 'DDP', name='incoterm'), nullable=True),
    sa.Column('estimated_departure', sa.Date(), nullable=True),
    sa.Column('estimated_arrival', sa.Date(), nullable=True),
    sa.Column('actual_departure', sa.Date(), nullable=True),
    sa.Column('actual_arrival', sa.Date(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('total_weight_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_reference_number'), 'shipments', ['reference_number'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_user_id'), 'shipments', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('COMMERCIAL_INVOICE', 'PACKING_LIST', 'CERTIFICATE_OF_ORIGIN', 'BILL_OF_LADING', 'CUSTOMS_DECLARATION', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'SENT', name='documentstatus'), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_shipment_id'), 'documents', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_id'), 'shipment_items', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_id'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_shipment_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_shipments_user_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_reference_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_freight_rates_origin_country_id'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_mode'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_id'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_effective_date'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_destination_country_id'), table_name='freight_rates')
    op.drop_table('freight_rates')
    op.drop_index(op.f('ix_duty_rates_importing_country_id'), table_name='duty_rates')
    op.drop_index(op.f('ix_duty_rates_id'), table_name='duty_rates')
    op.drop_index(op.f('ix_duty_rates_hs_code_id'), table_name='duty_rates')
    op.drop_table('duty_rates')
    op.drop_index(op.f('ix_hs_codes_id'), table_name='hs_codes')
    op.drop_index(op.f('ix_hs_codes_heading'), table_name='hs_codes')
    op.drop_index(op.f('ix_hs_codes_code'), table_name='hs_codes')
    op.drop_index(op.f('ix_hs_codes_chapter'), table_name='hs_codes')
    op.drop_table('hs_codes')
    op.drop_index(op.f('ix_exchange_rates_target_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_base_currency'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
